### PR TITLE
fix and refactor log merge policy, fixes #1035

### LINKED ISSUE #1035: LogMergePolicy set_max_merge_size not being respected
**Describe the bug**
- What did you do?
Configured the LogMergePolicy with max merge size and inserted 38M documents with a single final commit in the end.
```rust
let writer = index
    .writer(1024 * 1024 * 1024)
    .expect("failed to create writer");

let mut policy = tantivy::merge_policy::LogMergePolicy::default();
policy.set_max_merge_size(3_000_000);

writer.set_merge_policy(Box::new(policy));
```
- What happened?

Multiple 1M document segments merged into 9M document segments and two 9M document segments merged into a ~ 18M document segment
- What was expected?

The expected behavior was that no segment larger than 3M documents would be merged. As an aside, the desired behavior for my use case was to limit the maximum size of a segment to 3M documents in order to have enough segments to optimize parallelism.

**Which version of tantivy are you using?**
If "master",  ideally give the specific sha1 revision.

Version 13.2

**To Reproduce**

If your bug is deterministic, can you give a minimal reproducing code?
Some bugs are not deterministic. Can you describe with precision in which context it happened?
If this is possible, can you share your code?

The time required to reindex all documents is not trivial so no attempt was made to reproduce the bug

### PR DESCRIPTION
**Pull request by PSeitz**
fixes a bug in log merge policy where an index was wrongly referenced by its index

### CODE REVIEW

File: src/indexer/log_merge_policy.rs [hunk 1]
```diff
@@ -54,40 +54,35 @@ impl LogMergePolicy {
...
 impl MergePolicy for LogMergePolicy {
     fn compute_merge_candidates(&self, segments: &[SegmentMeta]) -> Vec<MergeCandidate> {
-        let mut size_sorted_tuples = segments
+        let mut size_sorted_segments = segments
             .iter()
-            .map(SegmentMeta::num_docs)
-            .enumerate()
-            .filter(|(_, s)| s <= &(self.max_merge_size as u32))
-            .collect::<Vec<(usize, u32)>>();
+            .filter(|s| s.num_docs() <= (self.max_merge_size as u32))
```
Comment (fulmicoton) [inline src/indexer/log_merge_policy.rs]: s/s/segment_meta/g please

File: src/indexer/log_merge_policy.rs [hunk 2]
```diff
@@ -54,40 +54,35 @@ impl LogMergePolicy {
...
-        if let Some(&(first_ind, first_score)) = size_sorted_log_tuples.first() {
-            let mut current_max_log_size = first_score;
-            let mut levels = vec![vec![first_ind]];
-            for &(ind, score) in (&size_sorted_log_tuples).iter().skip(1) {
-                if score < (current_max_log_size - self.level_log_size) {
-                    current_max_log_size = score;
+        if let Some(&(first_segment, log_size)) = sorted_segments_with_log_size.first() {
+            let mut current_max_log_size = log_size;
+            let mut levels = vec![vec![first_segment]];
+            for &(segment, segment_log_size) in (&sorted_segments_with_log_size).iter().skip(1) {
```
Comment (fulmicoton) [inline src/indexer/log_merge_policy.rs]: isn't it the same without the parenthesis and the &?

Comment (fulmicoton) [reply src/indexer/log_merge_policy.rs]:
```
for &(segment, segment_log_size) in sorted_segments_with_log_size.iter().skip(1) {
```

Comment (PSeitz) [reply src/indexer/log_merge_policy.rs]: yes, I assume someone started with an iter on the ref &sorted_segments_with_log_size and added the skip later

File: src/indexer/log_merge_policy.rs [hunk 3]
```diff
@@ -54,40 +54,35 @@ impl LogMergePolicy {
...
             levels
                 .iter()
                 .filter(|level| level.len() >= self.min_merge_size)
-                .map(|ind_vec| {
-                    MergeCandidate(ind_vec.iter().map(|&ind| segments[ind].id()).collect())
-                })
+                .map(|segments| MergeCandidate(segments.iter().map(|&seg| seg.id()).collect()))
                 .collect()
         } else {
             return vec![];
```
Comment (PSeitz) [inline src/indexer/log_merge_policy.rs]: this is dead code btw because of the early exit above

File: src/indexer/log_merge_policy.rs [hunk 4]
```diff
@@ -1,19 +1,20 @@
...
 use crate::core::SegmentMeta;
+use itertools::Itertools;
 use std::cmp;
 use std::f64;
 
 const DEFAULT_LEVEL_LOG_SIZE: f64 = 0.75;
 const DEFAULT_MIN_LAYER_SIZE: u32 = 10_000;
-const DEFAULT_MIN_MERGE_SIZE: usize = 8;
-const DEFAULT_MAX_MERGE_SIZE: usize = 10_000_000;
+const DEFAULT_MIN_NUM_SEGMENTS_IN_MERGE: usize = 8;
```
Comment (fulmicoton) [inline src/indexer/log_merge_policy.rs:9]: Thank you!
