### PR TITLE
Fix is_child_of function not considering the root facet.

### LINKED ISSUE #2085: Cannot collect facets starting from the root in Tantivy 0.20
Applying the following diff

```diff
diff --git a/src/collector/facet_collector.rs b/src/collector/facet_collector.rs
index 6861a9faa..597e4ba12 100644
--- a/src/collector/facet_collector.rs
+++ b/src/collector/facet_collector.rs
@@ -119,17 +119,16 @@ fn facet_depth(facet_bytes: &[u8]) -> usize {
 ///
 ///     {
 ///         let mut facet_collector = FacetCollector::for_field("facet");
-///         facet_collector.add_facet("/lang");
-///         facet_collector.add_facet("/category");
+///         facet_collector.add_facet("/");
 ///         let facet_counts = searcher.search(&AllQuery, &facet_collector)?;
 ///
 ///         // This lists all of the facet counts
 ///         let facets: Vec<(&Facet, u64)> = facet_counts
-///             .get("/category")
+///             .get("/")
 ///             .collect();
 ///         assert_eq!(facets, vec![
-///             (&Facet::from("/category/biography"), 1),
-///             (&Facet::from("/category/fiction"), 3)
+///             (&Facet::from("/lang"), 4),
+///             (&Facet::from("/category"), 4)
 ///         ]);
 ///     }
 ///
```

to the example for `FacetCollector` makes it fail with

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `[(Facet(/lang), 4)]`,
 right: `[(Facet(/lang), 4), (Facet(/category), 4)]`', src/collector/facet_collector.rs:59:9
```

using the just released Tantitvy version 0.20, i.e. it is not possible to collect facets starting with the root.

I am not sure what the problem is, but I suspect that `compute_collapse_mapping_one` does not handle `facet_bytes.len() == 0` which is the case when collecting facets from the root.

### PR DESCRIPTION
**Pull request by adamreichold**
I think this is basically the same issue as #1448 at another place in the code base.

Closes #2085

### CODE REVIEW

File: src/collector/facet_collector.rs [hunk 1]
```diff
@@ -789,6 +807,15 @@ mod tests {
         );
         Ok(())
     }
+
+    #[test]
+    fn is_child_facet() {
+        assert!(super::is_child_facet(&b"foo"[..], &b"foo\0bar"[..]));
```
Comment (PSeitz) [inline src/collector/facet_collector.rs:813]: Can you rename it to `is_child_or_root_facet`

Comment (adamreichold) [reply src/collector/facet_collector.rs:813]: You mean the test or the original function `is_child_facet`?

In case of the original function, I think the suggest name is a bit confusing because it supposedly returns true if the given facet is a child facet, i.e. information on the possible child facet, not the parent facet. `is_parent_or_root_facet` would be better if the case should be noted explicitly in the name but then again every facet is a child facet of the root facet, so the existing name fits IMHO, just the implementation lacks the one crucial check.

Comment (PSeitz) [reply src/collector/facet_collector.rs:813]: ah yes, you are right, I misunderstood how the function is used

**Review by PSeitz — APPROVED** [review]
