### PR TITLE
fix postcard compatibility for top_hits, add postcard test

### LINKED ISSUE #2347: Top Hits Agg Performance: Delay fetching `get_document_field_data` in top_hits
`get_document_field_data` is currently called for every document collected instead of the top hits.

### LINKED ISSUE #4840: sending a query with `top_hits` causes a panic
As reported by a user:
While testing quickwit, the following ES query triggers a panic

```json
{
  "query": {
    "bool": {
      "must": [
        {
          "multi_match": {
            "query": "GET POST",
            "fields": [
              "db_statement"
            ]
          }
        },
        {
          "range": {
            "duration": {
              "gte": 0.6,
              "lte": 0.9
            }
          }
        },
        {
          "range": {
            "timestamp": {
              "gte": "2024-03-27T14:00:00Z",
              "lte": "2024-03-27T14:10:00Z"
            }
          }
        }
      ]
    }
  },
  "aggs": {
    "top_hits": {
      "top_hits": {
        "size": 10,
        "_source": {
          "includes": [
            "db_statement",
            "duration",
            "timestamp"
          ]
        },
        "sort": [
          {
            "_score": "desc"
          }
        ]
      }
    }
  },
  "size": 0
}
```

The cause is that the fruit of the top_hits collector are not serializable.

```
thread 'thread 'quickwit-search-3quickwit-search-0' panicked at quickwit-search/src/collector.rsthread ':quickwit-search-1680' panicked at ' panicked at quickwit-search/src/collector.rsquickwit-search/src/collector.rs::68022:::
22680Collector fruit should be serializable.: SerializeSeqLengthUnknown:
:
Collector fruit should be serializable.: SerializeSeqLengthUnknown22
:
Collector fruit should be serializable.: SerializeSeqLengthUnknown
```

top_hits is not considered supported by quickwit at the moment, so in a sense this is ok.

Supporting it is not super simple as it requires coding the fetch docs phase.
We need either to support it, or fix the code to make sure we return an explicit error.

### PR DESCRIPTION
**Pull request by PSeitz**
fixes https://github.com/quickwit-oss/quickwit/issues/4840

Fix intermediate result postcard serialization by removing flatten
Fix intermediate result postcard deserialization by replacing `OwnedValue` (no self-describing formats)

Delay doc value fetchting to end of segment collection, closes https://github.com/quickwit-oss/tantivy/issues/2347
Fix naming and struct organization

### CODE REVIEW

File: src/aggregation/metric/mod.rs [hunk 1]
```diff
@@ -92,8 +96,9 @@ pub struct TopHitsVecEntry {
 
     /// Search results, for queries that include field retrieval requests
     /// (`docvalue_fields`).
-    #[serde(flatten)]
-    pub search_results: FieldRetrivalResult,
```
Comment (fulmicoton) [inline src/aggregation/metric/mod.rs:96]: this should have been `FieldRetrievalResult` too. 

Is it still used? Can we remove or rename it?

File: src/aggregation/metric/top_hits.rs [hunk 2]
```diff
@@ -175,11 +194,24 @@ impl RetrievalFields {
...
+    pub fn value_field_names(&self) -> Vec<&str> {
+        self.doc_value_fields.iter().map(|s| s.as_str()).collect()
+    }
+
     fn get_document_field_data(
         &self,
         accessors: &HashMap<String, Vec<DynamicColumn>>,
         doc_id: DocId,
-    ) -> FieldRetrivalResult {
+    ) -> IntermediateFieldRetrivalResult {
```
Comment (fulmicoton) [inline src/aggregation/metric/top_hits.rs]: Retrieval

File: src/aggregation/metric/top_hits.rs [hunk 3]
```diff
@@ -92,42 +94,59 @@ pub struct TopHitsAggregation {
...
+        let mut map = serializer.serialize_map(Some(1))?;
+        map.serialize_entry(field, order)?;
+        map.end()
+    }
+}
+
+impl<'de> Deserialize<'de> for KeyOrder {
+    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
+    where D: Deserializer<'de> {
+        let mut k_o = <HashMap<String, Order>>::deserialize(deserializer)?.into_iter();
```
Comment (fulmicoton) [inline src/aggregation/metric/top_hits.rs]: variable name...

File: src/aggregation/metric/top_hits.rs [hunk 4]
```diff
@@ -92,42 +94,59 @@ pub struct TopHitsAggregation {
...
 
-    fn resolve_field_names(&mut self, reader: &ColumnarReader) -> crate::Result<()> {
+impl TopHitsAggregation {
+    /// Validate and resolve field retrieval parameters
+    pub fn validate_and_resolve_field_names(
+        &mut self,
+        reader: &ColumnarReader,
+    ) -> crate::Result<()> {
         // Tranform a glob (`pattern*`, for example) into a regex::Regex (`^pattern.*$`)
         let globbed_string_to_regex = |glob: &str| {
```
Comment (fulmicoton) [inline src/aggregation/metric/top_hits.rs]: can we extract this function? (I know this is not from this PR but still)

File: src/aggregation/metric/top_hits.rs [hunk 5]
```diff
@@ -344,7 +366,7 @@ impl PartialEq for ComparableDocFeature {
 impl Eq for ComparableDocFeature {}
 
 #[derive(Clone, Serialize, Deserialize, Debug)]
-struct ComparableDocFeatures(Vec<ComparableDocFeature>, FieldRetrivalResult);
+struct ComparableDocFeatures(Vec<ComparableDocFeature>, IntermediateFieldRetrivalResult);
```
Comment (fulmicoton) [inline src/aggregation/metric/top_hits.rs]: Can we fix the terrible struct name and remove the 2 positional arguments and use a regular struct?

File: src/aggregation/metric/top_hits.rs [hunk 6]
```diff
@@ -344,7 +366,7 @@ impl PartialEq for ComparableDocFeature {
...
 
 impl Ord for ComparableDocFeatures {
     fn cmp(&self, other: &Self) -> std::cmp::Ordering {
```
Comment (fulmicoton) [inline src/aggregation/metric/top_hits.rs:366]: My understanding is that the `TopHitsCollector` needlessly access retrieved fields for every single document it collects. (Not even those who enter the Top K)

This is quite terrible. Can we at least open a ticket to fix this?

File: src/aggregation/metric/mod.rs (hunk 1 above)
Comment (PSeitz) [reply src/aggregation/metric/mod.rs:96]: It can't be `FieldRetrievalResult`, since postcard does not support flatten

File: src/aggregation/metric/top_hits.rs (hunk 6 above)
Comment (PSeitz) [reply src/aggregation/metric/top_hits.rs:366]: Yes, that's quite terrible, I opened an issue here:
https://github.com/quickwit-oss/tantivy/issues/2347

Comment (PSeitz) [reply src/aggregation/metric/top_hits.rs:366]: I fixed it in this PR, fields will be retrieved after segment collection now

File: src/aggregation/metric/top_hits.rs (hunk 5 above)
Comment (PSeitz) [reply src/aggregation/metric/top_hits.rs]: Yes, I did also do a pass on all the names and some comments

File: src/aggregation/metric/top_hits.rs (hunk 6 above)
Comment (fulmicoton) [reply src/aggregation/metric/top_hits.rs:366]: thx

File: src/aggregation/metric/top_hits.rs [hunk 7]
```diff
@@ -92,42 +94,59 @@ pub struct TopHitsAggregation {
...
 }
 
-/// Search query result for each matched document
-/// TODO: move this to a common module
+/// Intermediate Search query result for each matched document
+///
+/// Unlike the final result, this struct is postcard compatible.
 #[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
-pub struct FieldRetrivalResult {
+pub struct IntermediateFieldRetrivalResult {
```
Comment (fulmicoton) [inline src/aggregation/metric/top_hits.rs]: The correct spelling is `Retri*e*val`

File: src/aggregation/metric/top_hits.rs (hunk 3 above)
Comment (fulmicoton) [inline src/aggregation/metric/top_hits.rs]: Explicit variable names please

File: src/aggregation/metric/top_hits.rs [hunk 8]
```diff
@@ -1,7 +1,9 @@
 use std::collections::HashMap;
 use std::fmt::Formatter;
```
Comment (fulmicoton) [inline src/aggregation/metric/top_hits.rs]:
```suggestion
```

**Review by fulmicoton — APPROVED** [review]

**Review by fulmicoton — CHANGES_REQUESTED** [review]
ComparableDocFeatures

**Review by fulmicoton — APPROVED** [review]
