### PR TITLE
fixes race condition in Searcher

### LINKED ISSUE #1461: `Searcher` and its `SearcherGeneration` may reference a different set of segments
# Bug

With tantivy @ d24f31f965543e7ad300b4ce9965b27aef8f3be1,

ran into a situation where Gen 1 below of the Searcher has an inconsistent set of segment IDs referenced in its `SearcherGeneration` object. 

## Gen 0: good

```
Searcher(
	[
		Seg("2b9d1870"),
		Seg("de008a03"),
		Seg("1443006d"),
		Seg("ce5a247e"),
		Seg("70af8500"),
		Seg("7c542ba6")
	]
)

SearcherGeneration {
	segments: {
		Seg("1443006d"): Some(103364896),
		Seg("2b9d1870"): Some(103364896),
		Seg("70af8500"): Some(103364896),
		Seg("7c542ba6"): None,
		Seg("ce5a247e"): Some(103364896),
		Seg("de008a03"): Some(103364896),
	},
	generation_id: 0
}
```

## Gen 1: bad

```
Searcher(
	[
		Seg("2b9d1870"),
		Seg("de008a03"),
		Seg("1443006d"),
		Seg("ce5a247e"),
		Seg("70af8500"),
		Seg("68356e6c”),
	]
)

SearcherGeneration {
	segments: {
		Seg("1240c4ed"): None,
		Seg("1443006d"): Some(103367743),
		Seg("2b9d1870"): Some(103367743),
		Seg("5a475796"): None,
		Seg("7c542ba6"): Some(103367743),
		Seg("70af8500"): Some(103367743),
		Seg("ce5a247e"): Some(103367743),
		Seg("de008a03"): Some(103367743)
	},
	generation_id: 1,
}

```

# Reason

Looks like this may have been a regression introduced in 23fe73a6c0a0a9f9b0a263f7fa31b278a9a6101f cc @PSeitz 

In between the below calls to `open_segment_readers()` is potential for a race condition.

https://github.com/quickwit-oss/tantivy/blob/23fe73a6c0a0a9f9b0a263f7fa31b278a9a6101f/src/reader/mod.rs#L239
https://github.com/quickwit-oss/tantivy/blob/23fe73a6c0a0a9f9b0a263f7fa31b278a9a6101f/src/reader/mod.rs#L224

The solution seems to be to only call it once when creating a `Searcher`, this used to be the case before. And maybe we can add an assertion that the set of `SegmentId`s is identical.

### PR DESCRIPTION
**Pull request by PSeitz**
fixes #1461
fixes a race condition in Searcher, by avoiding repeated calls to open_segment_readers and passing them instead as argument

### CODE REVIEW

**Comment by fulmicoton** [comment]
@shikhar can you review https://github.com/quickwit-oss/tantivy/pull/1464

File: src/core/searcher.rs [hunk 1]
```diff
@@ -247,6 +247,14 @@ impl SearcherInner {
         generation: TrackedObject<SearcherGeneration>,
         doc_store_cache_size: usize,
     ) -> io::Result<SearcherInner> {
+        debug_assert_eq!(
```
Comment (fulmicoton) [inline src/core/searcher.rs]: As discussed in the other thread, I prefer having an actually assert here. (as opposed to debug_assert)

**Review by shikhar — COMMENTED** [review]
@PSeitz aside from clippy nits, LGTM

I did have one unrelated change I was sneaking into my PR, that I wanted to ask about. 

Is `Relaxed` memory order safe here? Both a load and store are happening, so `AcqRel` seems safer to me. And this is by no means a hot path so being conservative seems fair.

https://github.com/quickwit-oss/tantivy/blob/998b1263f6a28696ed35f685376cb612287fe840/src/reader/mod.rs#L212

File: src/reader/mod.rs [hunk 2]
```diff
@@ -204,7 +201,7 @@ impl InnerIndexReader {
         Ok(segment_readers)
     }
 
-    fn create_new_searcher_generation(
+    fn track_segment_readers_in_inventory(
```
Comment (shikhar) [inline src/reader/mod.rs:204]: The previous name seems better to me, since we are creating a `SearcherGeneration` and making sure to do it in a way that we track it int the inventory, and the inventory tracks `SearcherGeneration` not segment readers.

Comment (PSeitz) [reply src/reader/mod.rs:204]: my issue with the previous name was that it's not clear that inventory is used to track and not the source of the generation

**Comment by PSeitz** [comment]
> @PSeitz aside from clippy nits, LGTM
> 
> I did have one unrelated change I was sneaking into my PR, that I wanted to ask about.
> 
> Is `Relaxed` memory order safe here? Both a load and store are happening, so `AcqRel` seems safer to me. And this is by no means a hot path so being conservative seems fair.
> 
> https://github.com/quickwit-oss/tantivy/blob/998b1263f6a28696ed35f685376cb612287fe840/src/reader/mod.rs#L212

Yeah, I think there could be scenarios where simultaneous reloads are triggered at the same time from multiple threads.

**Comment by fulmicoton** [comment]
@shikhar The operation is still Atomic... I think we just want to ensure that the id delivered are unique, and Relaxed is sufficient for that. AcqRel stuff is about instruction reordering.

**Comment by PSeitz** [comment]
> @shikhar I think we just want to ensure that the id delivered are unique, and Relaxed is sufficient for that... That being said it is not a hot part of the code. We can use SeqCst and not sweat it.

I think it could be an issue when two threads increment, but due to weak fencing, we get two times the same value back. If now one of those callers has a new segment in their list, we have the same id to different `SearcherGeneration`.

It's very unlikely though, and on many platforms Relaxed is already AcqRel.

**Comment by adamreichold** [comment]
> I think it could be an issue when two threads increment, but due to weak fencing, we get two times the same value back.

The memory orderings mostly determine how _other_ memory accesses are ordered w.r.t. the atomic accesses, they do not affect the atomicity of an operation like `fetch_add`, i.e. multiple threads doing `fetch_add(1, Ordering::Relaxed)` will never see identical values (ignoring overflow).

However, their accesses to other memory locations that are shared with other threads will not be ordered w.r.t. the ID generation, e.g. their accesses to `searcher_generation_inventory` are do not necessarily reflect their accesses to `searcher_generation_counter`, meaning that a thread with lower ID might see the stores to the inventory of a thread with a higher ID.

While I suspect that this is not an issue (this would have involve unsafe code if I understand things correctly), my personal choice would be `Ordering::AcqRel` as well just to capture any implicit dependencies which I do not see ATM. (I would suggest avoiding `Ordering::SeqCst` as mixing those two orderings can have unexpected effects and sticking to `AcqRel` is often preferable if global ordering is not required as it is simpler to  reason about the explicit pairings between acquire and release operations to the same memory address.)

**Comment by fulmicoton** [comment]
> It's very unlikely though, and on many platforms Relaxed is already AcqRel.

This is a very bad argument :). Also ARM is pretty popular.

> we get two times the same value back

You cannot get two times the same value back... That's not what ordering is about.
The explanation here is ok:
https://en.cppreference.com/w/cpp/atomic/memory_order

...


Anyway let's defensively go for `Ordering::AcqRel`...

**Review by fulmicoton — APPROVED** [review]

**Comment by shikhar** [comment]
Thanks folks, I need to learn more about memory orderings :)
