### PR TITLE
Fix: Improve collapse_overlapped_ranges function

### LINKED ISSUE #2473: Incorrect range merging in snippet generation
### What did you do?

I tested the `collapse_overlapped_ranges` function in Tantivy's snippet generation module with duplicate and unsorted ranges. These ranges were obtained from using `generator.snippet_from_doc(&retrieved_doc)` in the snippet generation process.

### What happened?

The current implementation fails to correctly handle input that contains both duplicate and unsorted ranges. This leads to incorrect merging of ranges, which could affect snippet generation accuracy.

image

### What was expected?

The function should correctly handle duplicate and unsorted ranges, removing duplicates and merging overlapping or adjacent ranges as appropriate, especially considering these ranges are directly obtained from the snippet generation process.

## Which version of tantivy are you using?
Tantivy version 0.22.0

## To Reproduce

The current implementation of `collapse_overlapped_ranges` is as follows:

https://github.com/quickwit-oss/tantivy/blob/3d1c4b313a63a854214eea669a865837e146ee17/src/snippet/mod.rs#L270

This implementation fails in the following test case, which simulates the kind of input received from `generator.snippet_from_doc(&retrieved_doc)`:

```rust
#[test]
fn test_duplicate_and_unsorted_ranges() {
    let ranges = vec![0..3, 3..6, 0..3, 3..6];
    let result = collapse_overlapped_ranges(&ranges);
    assert_eq!(result, vec![0..3, 3..6]);
}
```

### PR DESCRIPTION
**Pull request by gezihuzi**
To fix: #2473 

- Refactor into separate sort_and_deduplicate_ranges and merge_overlapping_ranges functions
- Enhance sorting to consider both start and end of ranges
- Optimize merging logic to handle adjacent ranges
- Add comprehensive examples in function documentation
- Ensure proper handling of duplicate and unsorted input ranges
- Improve overall efficiency and readability of range collapsing algorithm

### CODE REVIEW

**Review by PSeitz — APPROVED** [review]

File: src/snippet/mod.rs [hunk 1]
```diff
@@ -257,40 +257,68 @@ fn select_best_fragment_combination(fragments: &[FragmentCandidate], text: &str)
...
+///
+/// ## Examples
+/// - [0..1, 2..3] -> [0..1, 2..3]  # no overlap
+/// - [0..1, 1..2] -> [0..2]  # adjacent, merged
+/// - [0..2, 1..3] -> [0..3]  # overlapping, merged
+/// - [0..3, 1..2] -> [0..3]  # second range is completely within the first
+/// - [0..3, 3..6, 0..3, 3..6] -> [0..6]  # duplicates removed, then merged
+pub fn collapse_overlapped_ranges(ranges: &[Range<usize>]) -> Vec<Range<usize>> {
+    let prepared = sort_and_deduplicate_ranges(ranges);
+    debug_assert!(is_sorted(prepared.iter().map(|range| range.start)));
```
Comment (PSeitz) [inline src/snippet/mod.rs]: that debug assert would be better placed in `merge_overlapping_ranges`

**Comment by PSeitz** [comment]
Thanks, really nice PR with tests and docs!
