### PR TITLE
Better mixed types support in aggs and fix serialization issue

### LINKED ISSUE #1967: IntermediateTermBucketResult on numeric types is not serializable to json
Number keys are not supported in JSON. 
Serialization fails for `FxHashMap<Key::F64(_), _>`

```rust 
#[derive(Default, Clone, Debug, PartialEq, Serialize, Deserialize)]
/// Term aggregation including error counts
pub struct IntermediateTermBucketResult {
    pub(crate) entries: FxHashMap<Key, IntermediateTermBucketEntry>,
    pub(crate) sum_other_doc_count: u64,
    pub(crate) doc_count_error_upper_bound: u64,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialOrd)]
/// The key to identify a bucket.
#[serde(untagged)]
pub enum Key {
    /// String key
    Str(String),
    /// `f64` key
    F64(f64),
}
```

### PR DESCRIPTION
**Pull request by PSeitz**
- Improve support for mixed types in JSON field aggregations (pick the right field, #1913)
- Resolve the issue with JSON serialization for numeric keys (fixes #1967)
- Add JSON round-trip test for term buckets
- Remove `u64_lenient`, as this is a footgun without the type
- move aggregation benchmarks

### CODE REVIEW

File: src/fastfield/readers.rs [hunk 1]
```diff
@@ -252,33 +252,43 @@ impl FastFieldReaders {
...
-    /// Returns the `u64` column used to represent any `u64`-mapped typed (i64, u64, f64, DateTime).
+    /// Returns the `u64` column used to represent any `u64`-mapped typed (String/Bytes term ids,
+    /// i64, u64, f64, DateTime).
     ///
     /// Returns Ok(None) for empty columns
     #[doc(hidden)]
-    pub fn u64_lenient_with_type(
+    pub fn u64_lenient_for_type(
         &self,
+        type_white_list: Option<&[ColumnType]>,
```
Comment (fulmicoton) [inline src/fastfield/readers.rs]:
```suggestion
        type_white_list_opt: Option<&[ColumnType]>,
```

File: src/fastfield/readers.rs [hunk 2]
```diff
@@ -252,33 +252,43 @@ impl FastFieldReaders {
...
         field_name: &str,
     ) -> crate::Result<Option<(Column<u64>, ColumnType)>> {
         let Some(resolved_field_name) = self.resolve_field(field_name)? else {
             return Ok(None);
         };
         for col in self.columnar.read_columns(&resolved_field_name)? {
+            if let Some(type_white_list) = type_white_list {
```
Comment (fulmicoton) [inline src/fastfield/readers.rs]: pls avoid shadowing  (when it is needless)

File: src/aggregation/agg_req_with_accessor.rs [hunk 3]
```diff
@@ -110,7 +131,11 @@ impl MetricAggregationWithAccessor {
             | MetricAggregation::Min(MinAggregation { field: field_name })
             | MetricAggregation::Stats(StatsAggregation { field: field_name })
             | MetricAggregation::Sum(SumAggregation { field: field_name }) => {
-                let (accessor, field_type) = get_ff_reader_and_validate(reader, field_name)?;
+                let (accessor, field_type) = get_ff_reader_and_validate(
+                    reader,
+                    field_name,
+                    Some(get_numeric_or_date_column_types()),
```
Comment (fulmicoton) [inline src/aggregation/agg_req_with_accessor.rs:137]: does it make sense to allow sum for dates?
(I guess it is does not matter all that much to return a nonsense answer to a nonsense request but...)

**Review by fulmicoton — APPROVED** [review]

File: src/aggregation/agg_req_with_accessor.rs (hunk 3 above)
Comment (PSeitz) [reply src/aggregation/agg_req_with_accessor.rs:137]: since the baseline with 1970 is arbitrary, no doesn't make sense
