### PR TITLE
Closes #1195

### LINKED ISSUE #1195: Logic Error for non-indexed facets
When adding facets which are not indexed merge fails.

```
thread 'merge_thread2' panicked at 'Logic Error in Tantivy (Please report). HierarchicalFact field should have required a`term_ordinal_mapping`.', /home/pascal/LinuxData/Development/tantivy/blockedbitp/src/
indexer/merger.rs:279:26
```

**Which version of tantivy are you using?**
master

**To Reproduce**

Paste in merger.rs
```
    #[test]
    fn test_non_index_facets() {
        {
            let mut schema_builder = schema::Schema::builder();
            let facet_field = schema_builder.add_facet_field("facet", STORED);
            let index_builder = Index::builder().schema(schema_builder.build());
            let index = index_builder.create_in_ram().unwrap();
            {
                let mut index_writer = index.writer_for_tests().unwrap();
                let index_doc = |index_writer: &mut IndexWriter, doc_facets: &[&str]| {
                    let mut doc = Document::default();
                    for facet in doc_facets {
                        doc.add_facet(facet_field, Facet::from(facet));
                    }
                    index_writer.add_document(doc);
                };

                index_doc(&mut index_writer, &["/top/a/firstdoc", "/top/b"]);
                index_doc(&mut index_writer, &["/top/a/firstdoc", "/top/b", "/top/c"]);
                index_doc(&mut index_writer, &["/top/a", "/top/b"]);
                index_doc(&mut index_writer, &["/top/a"]);

                index_writer.commit().expect("committed");
                index_doc(&mut index_writer, &["/top/a"]);

                index_doc(&mut index_writer, &["/top/b"]);
                index_writer.commit().expect("committed");
            }

            // Merging the segments
            {
                let segment_ids = index
                    .searchable_segment_ids()
                    .expect("Searchable segments failed.");
                let mut index_writer = index.writer_for_tests().unwrap();
                block_on(index_writer.merge(&segment_ids)).expect("Merging failed");
                index_writer.wait_merging_threads().unwrap();
            }
        }
    }
```

**Expected Behaviour**
Not sure, facets should be automatically flagged as indexed?

### PR DESCRIPTION
**Pull request by fulmicoton**

### CODE REVIEW

File: src/collector/facet_collector.rs [hunk 1]
```diff
@@ -472,7 +472,7 @@ mod tests {
     #[test]
     fn test_facet_collector_drilldown() -> crate::Result<()> {
         let mut schema_builder = Schema::builder();
-        let facet_field = schema_builder.add_facet_field("facet", INDEXED);
```
Comment (PSeitz) [inline src/collector/facet_collector.rs:475]: we could think about keeping INDEXED which would equal FacetOptions::default()?

Comment (fulmicoton) [reply src/collector/facet_collector.rs:475]: Yes it might help backward compatibility.
