### PR TITLE
fix docstore settings for temp docstore

### LINKED ISSUE #1565: Use optimized docstore settings for sorting
The docstore should have optimized settings when sorting is enabled.
The blocks should be tiny to allow random access on the documents. The compression should be LZ4 or None.

### PR DESCRIPTION
**Pull request by PSeitz**
fixes #1565

### CODE REVIEW

File: src/indexer/segment_serializer.rs [hunk 1]
```diff
@@ -24,12 +24,25 @@ impl SegmentSerializer {
...
-        let store_component = if remapping_required {
-            SegmentComponent::TempStore
+        let settings = segment.index().settings().clone();
+        let store_writer = if remapping_required {
+            let store_write = segment.open_write(SegmentComponent::TempStore)?;
+            StoreWriter::new(
+                store_write,
+                crate::store::Compressor::None,
+                0, // we want random access on the docs, so we choose a minimal block size. Every
+                // doc will be flushed
```
Comment (fulmicoton) [inline src/indexer/segment_serializer.rs]:
```suggestion
                // doc will get its own block.
```

File: src/indexer/segment_writer.rs [hunk 2]
```diff
@@ -393,7 +393,8 @@ fn remap_and_write(
             serializer
                 .segment()
                 .open_read(SegmentComponent::TempStore)?,
-            50,
+            1, /* The docstore is configured for tiny docs for fast random access, we don't need
+                * the the cache */
```
Comment (fulmicoton) [inline src/indexer/segment_writer.rs:397]:
```suggestion
                * the cache */
```

Comment (fulmicoton) [inline src/indexer/segment_writer.rs]:
```suggestion
            1, /* The docstore is configured to have one doc per block, and each doc is accessed only 
            once: we don't need caching. */
```

**Review by fulmicoton — APPROVED** [review]
