### PR TITLE
handle empty segments for merge

### LINKED ISSUE #1189: Investigate empty segment merge
An issue occurred where merge after commit selected only empty segments.  

```
thread 'merge_thread1' panicked at 'Unexpected error, empty readers in IndexMerger', src/indexer/merger.rs:330:16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'merge_thread1' panicked at 'You forgot to flush "00004481000000000000000000000000.term" before its writter got Drop. Do not rely on drop. This also occurs when the indexer crashed, so you may want to
 check the logs for the root cause.', src/directory/ram_directory.rs:49:13
stack backtrace:
```

Investigate if checking for non-empty segments before triggering a merge is sufficient. There are also different possible scenarios, when we end up with an empty segment:

- fresh new segments ends up with no docs after processing the deletes
- old segments ends up with no docs after processing deletes
- merged segment ends up with no docs after processing the deletes

**To Reproduce**

Change `test_functional_indexing_sorted` to run with 15threads

`let mut index_writer = index.writer_with_num_threads(15, 150_000_000)?;`

Maybe run in a loop or multiple times.

### PR DESCRIPTION
**Pull request by PSeitz**
Optionally create a segment on merge
Create no segment when all segments to merge are empty

fixes #1189

### CODE REVIEW

File: src/indexer/merger.rs [hunk 1]
```diff
@@ -200,6 +200,12 @@ impl IndexMerger {
                 readers.push(reader);
             }
         }
+
+        if readers.is_empty() {
+            let err_msg = format!("Can't merge, all segments are empty {:?}.", segments);
+            return Err(crate::TantivyError::InvalidArgument(err_msg));
```
Comment (fulmicoton) [inline src/indexer/merger.rs]: Can we do something better?
Instead of returning an error, we want such a merge operation to succeed, not produce any new segment but remove the previous segments.

Comment (PSeitz) [reply src/indexer/merger.rs]: I considered that, but `merge` seems to be the wrong operation that is triggered. Instead we could have another operation, like `remove` that is called when all segments are empty.
We should still safeguard the merge code, or allow it to be run on empty data.

Comment (fulmicoton) [reply src/indexer/merger.rs]: @PSeitz but  triggerring a merge over several segment and discoving that they all contain no docs is a legit case.

I don't think it needs to be a separate operation.

Comment (PSeitz) [reply src/indexer/merger.rs]: I think that merge by definition creates a new segment, so should we create an empty segment?

File: src/indexer/index_writer.rs [hunk 2]
```diff
@@ -515,7 +515,7 @@ impl IndexWriter {
     /// Merges a given list of segments
     ///
     /// `segment_ids` is required to be non-empty.
-    pub fn merge(&mut self, segment_ids: &[SegmentId]) -> FutureResult<SegmentMeta> {
```
Comment (fulmicoton) [inline src/indexer/index_writer.rs:516]: Can we return `FutureResult<Option<SegmentMeta>>` ?

It can be very useful for people building tooling.

File: src/indexer/index_writer.rs [hunk 3]
```diff
@@ -515,7 +515,7 @@ impl IndexWriter {
     /// Merges a given list of segments
     ///
     /// `segment_ids` is required to be non-empty.
```
Comment (fulmicoton) [inline src/indexer/index_writer.rs:517]: Document that this function may not result in the creation of a new segment.

File: src/indexer/segment_updater.rs [hunk 4]
```diff
@@ -573,35 +585,42 @@ impl SegmentUpdater {
...
-                                merge_operation.segment_ids(),
-                                advance_deletes_err
-                            );
-                            assert!(!cfg!(test), "Merge failed.");
-
-                            // ... cancel merge
-                            // `merge_operations` are tracked. As it is dropped, the
-                            // the segment_ids will be available again for merge.
-                            return Err(advance_deletes_err);
+                if let Some(mut after_merge_segment_entry) = after_merge_segment_entry.as_mut() {
```
Comment (fulmicoton) [inline src/indexer/segment_updater.rs]: clippy... it does need to be mut because it is a mut reference.

File: src/indexer/segment_updater.rs [hunk 5]
```diff
@@ -573,35 +585,42 @@ impl SegmentUpdater {
     fn end_merge(
         &self,
         merge_operation: MergeOperation,
-        mut after_merge_segment_entry: SegmentEntry,
-    ) -> crate::Result<SegmentMeta> {
+        mut after_merge_segment_entry: Option<SegmentEntry>,
+    ) -> crate::Result<Option<SegmentMeta>> {
         let segment_updater = self.clone();
-        let after_merge_segment_meta = after_merge_segment_entry.meta().clone();
+        let after_merge_segment_meta = after_merge_segment_entry
```
Comment (fulmicoton) [inline src/indexer/segment_updater.rs:591]: after_merge_segment_meta is not used below...

**Review by fulmicoton — APPROVED** [review]
See comments inline

File: src/indexer/segment_updater.rs (hunk 5 above)
Comment (PSeitz) [reply src/indexer/segment_updater.rs:591]: yes it's returned
